// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CAST(GETDATE() AS DATE)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfJoined = new DateOnly(1, 1, 1),
                            FirstName = "Ali",
                            JobTitle = "Backend Developer",
                            LastName = "Khalid",
                            Level = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            DateOfJoined = new DateOnly(1, 1, 1),
                            FirstName = "Lina",
                            JobTitle = "Frontend Developer",
                            LastName = "Hassan",
                            Level = "Mid"
                        },
                        new
                        {
                            Id = 3,
                            DateOfJoined = new DateOnly(1, 1, 1),
                            FirstName = "Salim",
                            JobTitle = "Full Stack Developer",
                            LastName = "Yousef",
                            Level = "Senior"
                        },
                        new
                        {
                            Id = 4,
                            DateOfJoined = new DateOnly(1, 1, 1),
                            FirstName = "Mona",
                            JobTitle = "DevOps Engineer",
                            LastName = "Ahmad",
                            Level = "Mid"
                        },
                        new
                        {
                            Id = 5,
                            DateOfJoined = new DateOnly(1, 1, 1),
                            FirstName = "Omar",
                            JobTitle = "QA Engineer",
                            LastName = "Sami",
                            Level = "Junior"
                        },
                        new
                        {
                            Id = 6,
                            DateOfJoined = new DateOnly(1, 1, 1),
                            FirstName = "Sara",
                            JobTitle = "Project Manager",
                            LastName = "Nabil",
                            Level = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
